### ISSUE TITLE
Issue with authorisation

### ISSUE THREAD

**Issue by Shreya549** [CodeChefVIT/eventify#6]
Google Calendar API has been used to add events to the Google Calendar. 
But the API is returning an error : "No access, refresh token or API key is set."

**Comment by L04DB4L4NC3R** [comment]
Fixed your error. Pushed the code. Seems like you had taken the docs from the wrong place

**Comment by L04DB4L4NC3R** [comment]
A few changes were added:

- [X] You didnt have a `.gitignore` file for ignoring credentials.json
- [X] No `package.json` file was there for tracking dependancies 
- [X] All of the event code was added in the `app.listen` callback to maintain sequentiality
