### ISSUE TITLE
Issue with date format

### ISSUE THREAD

**Issue by Shreya549** [CodeChefVIT/eventify#9]
I was trying to add events to my calendar. I am unable to do so due to error in Date Format.
I used .toISOString() to convert the date. But still there is some error.

Error : Invalid value for: "T" found, can only parse bare date string: 2019-10-13T00:00:00.000Z Have you accidentally used DateTime instead of a Date?

![image](https://user-images.githubusercontent.com/43725310/66703975-a6437880-ed35-11e9-8aeb-b5cf46861f56.png)

**Comment by L04DB4L4NC3R** [comment]
Where are you getting this date from?

**Comment by Shreya549** [comment]
I am getting this date from the frontend while entering date into the html form

**Comment by L04DB4L4NC3R** [comment]
You can choose a universal format like UTC or ISO while taking input in the frontend only. You can use JS (in the frontend) for this

**Comment by YashMeh** [comment]
@Shreya549 pass the date to the Date object while sending from frontend and then do .getMonth .getTime etc.
